// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package controllerswarm

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ArrayOfImmutableInt32 struct {
	objID int32
	keyID wasmlib.Key32
}

func (o ArrayOfImmutableInt32) Exists() bool {
	return wasmlib.Exists(o.objID, o.keyID, wasmlib.TYPE_ARRAY)
}

func (a ArrayOfImmutableInt32) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfImmutableInt32) GetInt32(index int32) wasmlib.ScImmutableInt32 {
	return wasmlib.NewScImmutableInt32(a.objID, wasmlib.Key32(index))
}

type ImmutableOccupancyGrid = ArrayOfImmutableInt32

type ArrayOfMutableInt32 struct {
	objID int32
	keyID wasmlib.Key32
}

func (o ArrayOfMutableInt32) Exists() bool {
	return wasmlib.Exists(o.objID, o.keyID, wasmlib.TYPE_ARRAY)
}

func (a ArrayOfMutableInt32) Clear() {
	wasmlib.Clear(a.objID)
}

func (a ArrayOfMutableInt32) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfMutableInt32) GetInt32(index int32) wasmlib.ScMutableInt32 {
	return wasmlib.NewScMutableInt32(a.objID, wasmlib.Key32(index))
}

type MutableOccupancyGrid = ArrayOfMutableInt32
