// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package agentswarm

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	ScName        = "agentswarm"
	ScDescription = "A smart contract to keep maps on-ledger"
	HScName       = wasmlib.ScHname(0x0aaeb5d5)
)

const (
	ParamAgent      = wasmlib.Key("agent")
	ParamController = wasmlib.Key("controller")
	ParamMap        = wasmlib.Key("map")
)

const (
	ResultMissionID = wasmlib.Key("missionID")
	ResultPossition = wasmlib.Key("possition")
)

const (
	StateController     = wasmlib.Key("controller")
	StateMissionID      = wasmlib.Key("missionID")
	StatePossition      = wasmlib.Key("possition")
	StateSubmittedAgent = wasmlib.Key("submittedAgent")
	StateSubmittedMaps  = wasmlib.Key("submittedMaps")
)

const (
	FuncInit           = "init"
	FuncRegister       = "register"
	FuncRequestMission = "requestMission"
	FuncSubmitLastMap  = "submitLastMap"
	FuncUploadMap      = "uploadMap"
	ViewGetMission     = "getMission"
)

const (
	HFuncInit           = wasmlib.ScHname(0x1f44d644)
	HFuncRegister       = wasmlib.ScHname(0x3f559b22)
	HFuncRequestMission = wasmlib.ScHname(0xa08db104)
	HFuncSubmitLastMap  = wasmlib.ScHname(0x90f6e9b1)
	HFuncUploadMap      = wasmlib.ScHname(0x620b1843)
	HViewGetMission     = wasmlib.ScHname(0x0b183a65)
)
