// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package agentswarm

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

const (
	IdxParamAgent          = 0
	IdxParamController     = 1
	IdxParamMap            = 2
	IdxResultMissionID     = 3
	IdxResultPossition     = 4
	IdxStateController     = 5
	IdxStateMissionID      = 6
	IdxStatePossition      = 7
	IdxStateSubmittedAgent = 8
	IdxStateSubmittedMaps  = 9
)

const keyMapLen = 10

var keyMap = [keyMapLen]wasmlib.Key{
	ParamAgent,
	ParamController,
	ParamMap,
	ResultMissionID,
	ResultPossition,
	StateController,
	StateMissionID,
	StatePossition,
	StateSubmittedAgent,
	StateSubmittedMaps,
}

var idxMap [keyMapLen]wasmlib.Key32
