// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package agentswarm
import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ImmutableInitParams struct {
	id int32
}

func (s ImmutableInitParams) Controller() wasmlib.ScImmutableChainID {
	return wasmlib.NewScImmutableChainID(s.id, idxMap[IdxParamController])
}

type MutableInitParams struct {
	id int32
}

func (s MutableInitParams) Controller() wasmlib.ScMutableChainID {
	return wasmlib.NewScMutableChainID(s.id, idxMap[IdxParamController])
}

type ImmutableRegisterParams struct {
	id int32
}

func (s ImmutableRegisterParams) Agent() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamAgent])
}

type MutableRegisterParams struct {
	id int32
}

func (s MutableRegisterParams) Agent() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamAgent])
}

type ImmutableRequestMissionParams struct {
	id int32
}

func (s ImmutableRequestMissionParams) Agent() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamAgent])
}

type MutableRequestMissionParams struct {
	id int32
}

func (s MutableRequestMissionParams) Agent() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamAgent])
}

type ImmutableUploadMapParams struct {
	id int32
}

func (s ImmutableUploadMapParams) Agent() wasmlib.ScImmutableAgentID {
	return wasmlib.NewScImmutableAgentID(s.id, idxMap[IdxParamAgent])
}

func (s ImmutableUploadMapParams) Map() ImmutableOccupancyGrid {
	return ImmutableOccupancyGrid{objID: s.id, keyID: idxMap[IdxParamMap]}
}

type MutableUploadMapParams struct {
	id int32
}

func (s MutableUploadMapParams) Agent() wasmlib.ScMutableAgentID {
	return wasmlib.NewScMutableAgentID(s.id, idxMap[IdxParamAgent])
}

func (s MutableUploadMapParams) Map() MutableOccupancyGrid {
	return MutableOccupancyGrid{objID: s.id, keyID: idxMap[IdxParamMap]}
}
